# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  ## QueueProcessor
  queueprocessor:
    image: mcr.microsoft.com/dotnet/sdk:10.0@sha256:f061e5a7532b36fa1d1b684857fe1f504ba92115b9934f154643266613c44c62
    command: ["dotnet", "watch", "run", "--no-hot-reload"]
    working_dir: /app
    volumes:
      - ./src/queue-processor:/app
    environment:
      ASPNETCORE_URLS: http://*:5000
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - dapr-demo-network
  queueprocessor-dapr:
    image: daprio/daprd:1.17.3@sha256:7d0fc04a9ff116dd05fd8eabd86a09d885a252235903defb6f781225153793c4
    command: ["./daprd",
     "--app-id", "queueprocessor",
     "--app-port", "5000",
     "--resources-path", "/components",
     "--config", "/configuration/configuration.yaml"]
    volumes:
      - ./compose/configuration/:/configuration
      - ./compose/components/:/components
    network_mode: service:queueprocessor

  redis:
    image: redis:8@sha256:009cc37796fbdbe1b631b4cc0582bed167e5e403ed8bcd06f77eb6cb5aeb6f93
    ports:
      - 6379:6379
    networks:
      - dapr-demo-network

networks:
  dapr-demo-network:
