# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  jaeger:
    image: jaegertracing/jaeger:2.17.0@sha256:6266573208d665ce5c17483bce0a75d0806480d92c84766d288d0aee885ce708
    ports:
      - "${JAEGER_QUERY_HOST_PORT:-16686}:16686"
      - "${JAEGER_OTLP_GRPC_HOST_PORT:-4317}:4317"
      - "${JAEGER_OTLP_HTTP_HOST_PORT:-4318}:4318"
    networks:
      - dapr-demo-network

networks:
  dapr-demo-network:
    name: dapr-demo-network
    external: false
