# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  jaeger:
    image: jaegertracing/jaeger:2.17.0@sha256:6266573208d665ce5c17483bce0a75d0806480d92c84766d288d0aee885ce708
    ports:
      - 16686:16686
      - 4317:4317 # OtlpgRPC
      - 4318:4318 # OtlpHttp

